name: Python code minimum supported version check with vermin

on:
  push:
    paths:
      - '!tests/**/*.py'
      - '**/*.py'
  pull_request:
    paths:
      - '!tests/**/*.py'
      - '**/*.py'

jobs:
  vermin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 1 }}
      # vermin version should be kept in sync with .pre-commit-config.yaml
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          check-latest: true
          pip-install: vermin==1.8.0
      - name: Collect changed files list
        id: collect
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
              echo "changed=$(git diff --name-only --diff-filter=ACMRT -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
          else
              echo "changed=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
          fi
      - name: Run vermin
        run: |
          FILES_LIST="${{ steps.collect.output.changed }}"
          [[ ! -z "$FILES_LIST" ]] && vermin --target=3.8- --no-parse-comments --no-tips --violations --backport argparse --format=github $FILES_LIST
